AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Quiet AWS News
  
  AWS What's New, but only for what you're interested in

Parameters:
  webhookurl:
    Description: chime webhook url to post to
    Type: String
    Default: ""

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  newsFunc:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bin/
      Handler: news
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Schedule
          Properties:
            Schedule: cron(0 6 * * ? *)
                        # 06***
        debug:
          Type: Api
          Properties:
            Path: /debug
            Method: GET

      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          webhook: 
            Ref: webhookurl

Outputs:
  newsFunc:
    Description: "First Lambda Function ARN"
    Value: !GetAtt newsFunc.Arn

  newsFuncIamRole:
    Description: "Implicit IAM Role created for news function"
    Value: !GetAtt newsFunc.Arn